# Generated by Django 4.2.4 on 2023-08-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_spaces_space'),
        ('outh', '0002_rename_users_user'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminders',
            new_name='Reminder',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
