# Generated by Django 4.2.4 on 2023-09-18 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0010_space_max_occupancy_alter_space_occupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminder',
            new_name='Reminde',
        ),
    ]
