# Generated by Django 4.2.4 on 2023-09-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0010_space_max_occupancy_alter_space_occupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Spaces', '0002_rename_reminder_reminde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('remember_to', models.DateTimeField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
