# Generated by Django 4.2.4 on 2023-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Reminde',
        ),
    ]
