# Generated by Django 4.2.4 on 2023-09-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0004_alter_notification_id_delete_reminde'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(default='0001-01-01 00:00:00'),
        ),
    ]
