# Generated by Django 4.2.4 on 2023-09-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0005_notification_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_time',
        ),
    ]
