# Generated by Django 4.2.4 on 2023-10-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0007_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent',
        ),
    ]
