# Generated by Django 4.2.4 on 2023-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0009_notification_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
