# Generated by Django 4.2.4 on 2023-10-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0011_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
