# Generated by Django 4.2.4 on 2023-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('availability', models.IntegerField()),
                ('clasification', models.IntegerField()),
            ],
        ),
    ]
