# Generated by Django 4.2.4 on 2023-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('availability', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Ocupado'), (2, 'Deshabilitado')])),
                ('clasification', models.IntegerField(choices=[(0, 'Escenario deportivo'), (1, 'Mesa de restaurante'), (2, 'Zona de descanso')])),
            ],
        ),
    ]
