# Generated by Django 4.2.4 on 2023-08-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('spaces', '0001_initial'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spaces',
            new_name='Space',
        ),
    ]
