# Generated by Django 4.2.4 on 2023-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0002_rename_clasification_space_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
