# Generated by Django 4.2.4 on 2023-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_spaces_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(),
        ),
    ]
