# Generated by Django 4.2.4 on 2023-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_space_latitude_space_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
