# Generated by Django 4.2.4 on 2023-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_space_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='availability',
            field=models.IntegerField(choices=[('Disponible', 0), ('Ocupado', 1), ('Deshabilitado', 2)]),
        ),
    ]
