# Generated by Django 4.2.4 on 2023-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0005_alter_space_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(default='/images/spaces/piscina.jpg', upload_to='spaces/images'),
        ),
    ]
