# Generated by Django 4.2.4 on 2023-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_space_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='clasification',
            field=models.IntegerField(choices=[(0, 'Escenario deportivo'), (1, 'Mesa de restaurante'), (2, 'Zona de descanso')]),
        ),
    ]
