# Generated by Django 4.2.4 on 2023-08-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_spaces_space'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OcuppiedSpaces',
            new_name='OcuppiedSpace',
        ),
    ]
