# Generated by Django 4.2.4 on 2023-09-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_m_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_m',
            name='profile_pic',
            field=models.ImageField(default='p1.png', null=True, upload_to=''),
        ),
    ]
