# Generated by Django 4.2.4 on 2023-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_m_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_m',
            name='profile_pic',
            field=models.ImageField(default='images/p1.png', null=True, upload_to=''),
        ),
    ]
