# Generated by Django 4.2.4 on 2023-09-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_m_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_m',
            name='email',
        ),
    ]
