# Generated by Django 4.2.4 on 2023-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_user_m_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_m',
            name='profile_pic',
            field=models.ImageField(default='images/profile.jpg', null=True, upload_to=''),
        ),
    ]
