# Generated by Django 4.2.4 on 2023-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_user_m_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_m',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', null=True, upload_to=''),
        ),
    ]
