# Generated by Django 4.2.4 on 2023-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_user_m_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_m',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
