# Generated by Django 4.2.4 on 2023-11-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_user_m_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_m',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='user/images'),
        ),
    ]
